# Generated by Django 3.0.7 on 2020-10-03 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20201003_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='author',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='date_posted',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='email',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='link',
        ),
    ]
